### PR TITLE
breaking(integration_test_charm.yaml): Remove `jhack tail` logs

### LINKED ISSUE #223: Timeout on jhack tail (integration_test_charm.yaml)
jhack tail takes longer than 3 minutes when debug log is large
e.g. https://github.com/canonical/mongodb-operator/actions/runs/10276480008/job/28437246655#step:33:1

not exactly sure what's the root cause, it appears to be related to log size but not only that

the previously linked run has 74.8 MB debug log

this run has two models each with a 4.0 MB log: https://github.com/canonical/postgresql-operator/actions/runs/10276476581/job/28437198646 (jhack tail takes 1:19)

this run has a 13.6 MB log: https://github.com/canonical/mongodb-operator/actions/runs/10276480008/job/28437244101#step:33:7 (jhack tail takes >3 min)

reported by @taurus-forever

### PR DESCRIPTION
**Pull request by carlcsaposs-canonical**
Fixes #223

### CODE REVIEW

**Comment by taurus-forever** [comment]
Does it mean: impossible to speedup `jhack tail`?
It was really useful to see it events... a lot of new questions appear, e.g.:
1) Why juju stop sending update-status to mysql/1 and mysql/2 [here](https://github.com/canonical/mysql-k8s-operator/actions/runs/10276456187/job/28437326108#step:33:11)
2) Why no events from `02:29:18` to `03:43:09`
and more...

**Comment by taurus-forever** [comment]
Proposal: do we see the log file size? Can we skip jhack tail run for huge logs only (or limit it to last 10000 lines of the log, etc)?

**Review by taurus-forever — APPROVED** [review]
Sad.

**Review by dragomirp — APPROVED** [review]

**Comment by PietroPasotti** [comment]
I take it the `--output` flag didn't work?

**Comment by PietroPasotti** [comment]
mm, too bad. Tomorrow I have some time to look at an optimization for --output mode

**Pull request merged**
