### PR TITLE
compatible: Add pytest_plugins/microceph

### LINKED ISSUE #111: Add microceph action as an optional step in the reusable `intergration_test_charm`  workflow
In order to test backup/restore to ceph, we need to make sure the microceph action is run on the runner running the `integration_test_charm` workflow.

Since most repositories won't use it (at least now), make it an optional step.

### PR DESCRIPTION
**Pull request by carlcsaposs-canonical**
Pytest plugin with fixture to set up microceph & return credentials

Fixes #111

Derived from https://github.com/canonical/microceph-action

### CODE REVIEW

**Review by paulomach — COMMENTED** [review]
Nice, thank you. Although this will suffice for the current mysql tests requirements*, I ask if it's too expensive to also setup nginx to provide https testing.

@phvalguima comments?

_*currently, xbcloud is not working with self-signed certs_

**Comment by paulomach** [comment]
> @paulomach do the current microceph mysql tests in [canonical/mysql-k8s-operator#332](https://github.com/canonical/mysql-k8s-operator/pull/332) use https?

that's the point: no due a current issue with xbcloud (the backup streaming component) and self-signed certs.
But other potential users may want to.
So, I'm not blocking the PR, just checking the effort

**Review by taurus-forever — APPROVED** [review]
I Like it! LGTM!

**Comment by phvalguima** [comment]
LGTM

One thing I noticed is that you jumped the step:
```
sudo microceph.radosgw-admin key create --uid=test --key-type=s3 --access-key "${ACCESS_KEY}" --secret-key "${SECRET_KEY}"
```
Afair, that was added to allow the user to choose the keys.

Indeed it is missing https but self-signed certs has been shown as an issue for OpenSearch as well. Eventually, we've settled for http only.
I agree with @paulomach, we need to get the self-signed right, as this is a common pattern. We can merge this change and open a ticket to keep track of the remaining microceph https work.

**Review by phvalguima — APPROVED** [review]

**Review by paulomach — APPROVED** [review]
thank you

**Pull request merged**
